name: 'Set up Java'
description: 'Sets up Java for compilation'
inputs:
  working-directory:
    description: 'The directory containing the top-level pom'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: (Java) Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        server-id: cloudsmith-api-contracts
        server-username: CLOUDSMITH_USERNAME
        server-password: CLOUDSMITH_API_KEY

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: '~/.m2/repository'
        key: maven-deps-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}/**/pom.xml', inputs.working-directory)) }}
