name: 'Set up Go'
description: 'Sets up go and protoc for compilation.'
inputs:
  github-token:
    description: 'GITHUB_TOKEN secret to avoid rate limiting'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup golang
      uses: actions/setup-go@v4.0.1

    - name: Setup protoc
      uses: arduino/setup-protoc@v1.3.0
      with:
        repo-token: ${{ inputs.github-token }}

    - name: Setup protoc-gen-go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      shell: bash
