name: Publish Flow Contracts Java Library

on:
  push:
    branches:
      - 'master'
    paths:
      - 'flows-contracts/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'flows-contracts/**'

jobs:
  java:
    name: Java library
    uses: ./.github/workflows/reusable/maven-library.yml
    secrets: inherit
    with:
      working-directory: 'flows-contracts'
      publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
  go:
    name: Go module
    uses: ./.github/workflows/reusable/go-module.yml
    secrets: inherit
    with:
      working-directory: 'flows-contracts'
      publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
