name: Flows Contracts Release

on:
  push:
#    branches:
#      - 'master'
    paths:
      - 'flows-contracts/**'

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release.yml
    with:
      working-directory: 'flows-contracts'
