name: Flows Contracts Test

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'flows-contracts/**'

jobs:
  java:
    name: Java library
    uses: ./.github/workflows/maven-library-test.yml
    with:
      working-directory: 'flows-contracts'
  go:
    name: Go module
    uses: ./.github/workflows/go-module-test.yml
    with:
      working-directory: 'flows-contracts'
