name: TODO - Go Module

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'This workflow is a stub'
        required: true
        type: string

jobs:
  build-and-publish:
    name: TODO - Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup golang
        uses: actions/setup-go@v3

      - name: Build library
        run: echo "This workflow is a stub"
        shell: bash
        working-directory: ${{ inputs.working-directory }}
