name: Go Module

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'This workflow is a stub'
        required: true
        type: string
      publish:
        description: 'This workflow is a stub'
        required: true
        type: boolean

defaults:
  run:
    shell: bash
    working-directory: ${{ inputs.working-directory }}

jobs:
  build-and-publish:
    name: Build and publish Maven library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup golang
        uses: actions/setup-go@v3

      - name: Build library
        run: echo "This workflow is a stub"
