name: Go Module Test

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Root directory of the Go module'
        required: true
        type: string

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup golang
        uses: actions/setup-go@v4.0.1

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.3.0

      - name: Setup protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Build library
        run: ./build.sh
        shell: bash
        working-directory: ${{ inputs.working-directory }}
