name: Maven Library

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory that contains the library''s main POM file'
        required: true
        type: string

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: '~/.m2/repository'
          key: maven-deps-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}/**/pom.xml', inputs.working-directory)) }}

      - name: Build library
        run: mvn -B verify
        shell: bash
        working-directory: ${{ inputs.working-directory }}

      - name: Upload library artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 'jar-files'
          path: ${{ format('{0}/**/target/*.jar', inputs.working-directory) }}
