name: Maven Library

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory that contains the library''s main POM file'
        required: true
        type: string
      publish:
        description: 'Toggles the deployment of the library to a Maven repository'
        required: true
        type: boolean
    secrets:
      github-token:
        description: 'The GITHUB_TOKEN secret passed from the caller workflow'
        required: false

jobs:
  build-and-publish:
    name: Build and publish Maven library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: '~/.m2/repository'
          key: maven-deps-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}/**/pom.xml', inputs.working-directory)) }}

      - name: Build library
        run: mvn -B install
        shell: bash
        working-directory: ${{ inputs.working-directory }}

      - name: Publish library
        if: ${{ inputs.publish }}
        run: mvn -B deploy:deploy
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}

      - name: Upload library artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 'jar-files'
          path: ${{ format('{0}/**/target/*.jar', inputs.working-directory) }}
