name: Maven Library Release

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory that contains the library''s main POM file'
        required: true
        type: string
    secrets:
      CLOUDSMITH_API_KEY:
        required: true

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          server-id: cloudsmith-api-contracts
          server-username: github-actions
          server-password: CLOUDSMITH_API_KEY

      - name: Configure runner for committing
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: '~/.m2/repository'
          key: maven-deps-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}/**/pom.xml', inputs.working-directory)) }}

      - name: Release library
        run: mvn -B release:prepare release:perform
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Upload library artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 'jar-files'
          path: ${{ format('{0}/**/target/*.jar', inputs.working-directory) }}
