name: Minion Certificate Manager Release

on:
  push:
    branches:
      - 'master'
    paths:
      - 'minion-certificate-manager/**'

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release.yml
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    with:
      working-directory: 'minion-certificate-manager'
